name: 'Svelte Check for PRs'
description: 'Provides a Svelte Check readout on the files in a Pull Request'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
    icon: 'search'
    color: 'orange'

inputs:
    paths:
        description: 'The path(s) to run svelte-check from, one per line'
        required: false
        default: '.'
    filterChanges:
        description: 'When true only the files that change (in the pull request) will be checked'
        required: false
        default: 'true'

runs:
    using: 'node20'
    main: 'dist/index.js'
