name: demo

on:
  - pull_request
  - workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
            version: 8.12.1

      - name: Install
        run: pnpm install

      - name: Run the action
        uses: ghostdevv/svelte-check-action@main
        with:
          paths: ./test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
