name: demo

on:
    - pull_request
    - workflow_dispatch

permissions: {}

# Please view the README for a complete example action
# This is setup to run the changes, as well as the specific node version
# we're targeting

jobs:
    demo:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write # Required to be able to comment on PRs
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup PNPM
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

            - name: Setup Node 20.20.2
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 20.20.2
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            - name: Install
              run: pnpm install

            - name: svelte-check
              uses: ./ # in prod: ghostdevv/svelte-check-action
              with:
                  paths: ./test
                  filterChanges: false
