name: Tagger

on:
    release:
        types: [created, edited]

jobs:
    actions-tagger:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Tag Release
              uses: stevenjdh/action-tagger@534fa1533fe939d77268fb5b89dfb09c41edca35 # v1.1.0
              with:
                  set-latest-tag: true
