name: Tagger

on:
    release:
        types: [created, edited]

permissions: {}

jobs:
    actions-tagger:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Allow tagger to write the tags
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Tag Release
              uses: stevenjdh/action-tagger@534fa1533fe939d77268fb5b89dfb09c41edca35 # v1.1.0
              with:
                  set-latest-tag: true
